name: barista_log
description: "A coffee tracking app."
publish_to: 'none' 
version: 2.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The Ingredients we added:
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.19.0
  csv: ^6.0.0
  path_provider: ^2.1.2
  share_plus: ^10.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#6D4C41"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true